name: Check PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    name: Check PR title
    steps:
      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - uses: amannn/action-semantic-pull-request@v3.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
